app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 10s
  max-updated-records-value: 5
  database-access-type: jpa
  githubUrl: https://api.github.com
  stackoverflowUrl: https://api.stackexchange.com/2.3
  botUrl: http://localhost:8090/
  retryProperties:
    type: linear
    statuses: [ 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511 ]
    attempts: 3
    delay: 10s
  useQueue: true
  kafka:
    bootstrap-servers: localhost:29092
    topicName: "linkUpdates"

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: (/api/tg-chat/.*)|(/api/links)
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API request quota\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 5
              unit: seconds
