app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  max-updated-records-value: 5
  githubUrl: https://api.github.com
  stackoverflowUrl: https://api.stackexchange.com/2.3
  botUrl: http://localhost:8090/

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
